version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: foodgo
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234

  api_server:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - ./:/app
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh mysql:3306 -s -t 100
        ./start.sh

volumes:
  mysql-data:
